import {readSpectrumFile,styleFileInput} from './import.js?v=7';
import {parseQuery,matchBands,parseCSV,detectPeaks} from './science.js?v=7';
import {buildReport,reportCSV,reportHTML} from './report.js?v=7';
import {preprocess,compareSpectra} from './processing.js?v=7';
import {patterns} from './references.js?v=7';
const $=id=>document.getElementById(id);
let zoom=null;let spectrum=null,query=parseQuery('1715'),peaks=[];
let processed=null,comparison=null,referencePoints=null;
const number=n=>Number(n.toFixed(2)).toLocaleString('en-US',{maximumFractionDigits:2});
function status(message){$('status').textContent=message;}
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function svgElement(tag,attributes){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attributes))e.setAttribute(k,v);return e;}
function plot(matches){
 const svg=svgElement('svg',{viewBox:'0 0 800 300',role:'img','aria-label':spectrum?'Raw spectrum with candidate peak markers; wavenumber decreases from left to right':'Reference band ranges on a decreasing wavenumber axis'});
 const fullLo=spectrum?Math.min(spectrum.points[0].x,400):400,fullHi=spectrum?Math.max(spectrum.points.at(-1).x,4000):4000;
 const lo=zoom?.min??fullLo,hi=zoom?.max??fullHi;const x=n=>56+(hi-n)/(hi-lo)*720;
 let min=0,max=1;if(spectrum){min=Math.min(...spectrum.points.map(p=>p.y),...(processed??[]).map(p=>p.y));max=Math.max(...spectrum.points.map(p=>p.y),...(processed??[]).map(p=>p.y));if(min===max)max=min+1;}
 const y=n=>244-(n-min)/(max-min)*205;
 for(let i=0;i<5;i++){const yy=39+i*51.25;svg.append(svgElement('line',{x1:56,x2:776,y1:yy,y2:yy,stroke:'#e9eaed'}));const t=svgElement('text',{x:45,y:yy+4,'text-anchor':'end',fill:'#65666d','font-size':11});t.textContent=spectrum?number(max-i*(max-min)/4):'';svg.append(t);}
 const shade=(a,b,opacity)=>{if(b<lo||a>hi)return;svg.append(svgElement('rect',{x:x(Math.min(b,hi)),y:35,width:Math.max(2,x(Math.max(a,lo))-x(Math.min(b,hi))),height:210,fill:'#0066cc',opacity}));};for(const b of matches)shade(b.min,b.max,'.08');shade(query.min,query.max,'.18');
 if(spectrum){svg.append(svgElement('polyline',{points:spectrum.points.filter(p=>p.x>=lo&&p.x<=hi).map(p=>`${x(p.x)},${y(p.y)}`).join(' '),fill:'none',stroke:'#286eaa','stroke-width':1.7,'stroke-linejoin':'round'}));for(const p of peaks.filter(p=>Number.isFinite(p.y)&&p.x>=lo&&p.x<=hi))svg.append(svgElement('circle',{cx:x(p.x),cy:y(p.y),r:4,fill:'#0066cc',stroke:'white','stroke-width':2}));}
 else{const t=svgElement('text',{x:416,y:133,'text-anchor':'middle',fill:'#65666d','font-size':14});t.textContent='Import a spectrum to see your measurements';svg.append(t);}
 for(const n of Array.from({length:7},(_,i)=>hi-(hi-lo)*i/6)){const t=svgElement('text',{x:x(n),y:270,'text-anchor':'middle',fill:'#65666d','font-size':11});t.textContent=number(n);svg.append(t);}
 const label=svgElement('text',{x:416,y:296,'text-anchor':'middle',fill:'#65666d','font-size':11});label.textContent='Wavenumber (cm⁻¹)';svg.append(label);
 if(spectrum){const intensity=svgElement('text',{x:56,y:18,fill:'#65666d','font-size':11});intensity.textContent=$('type').value==='transmittance'?'Transmittance (%)':'Absorbance';svg.append(intensity);}
 if(processed&&spectrum){svg.append(svgElement('polyline',{points:processed.filter(p=>p.x>=lo&&p.x<=hi).map(p=>`${x(p.x)},${y(p.y)}`).join(' '),fill:'none',stroke:'#c05b15','stroke-width':1.5}));}
 if(referencePoints){const rmin=Math.min(...referencePoints.map(p=>p.y)),rmax=Math.max(...referencePoints.map(p=>p.y));if(rmax>rmin)svg.append(svgElement('polyline',{points:referencePoints.filter(p=>p.x>=lo&&p.x<=hi).map(p=>x(p.x)+','+y(min+(p.y-rmin)/(rmax-rmin)*(max-min))).join(' '),fill:'none',stroke:'#7b46a2','stroke-width':1.4,'stroke-dasharray':'5 3'}));} svg.onclick=e=>{if(!spectrum||!$('chart-pick').checked)return;const r=svg.getBoundingClientRect(),sx=(e.clientX-r.left)/r.width*800,sy=(e.clientY-r.top)/r.height*300;if(sx<56||sx>776||sy<35||sy>244)return;const wave=hi-(sx-56)/720*(hi-lo),point=spectrum.points.reduce((a,p)=>Math.abs(p.x-wave)<Math.abs(a.x-wave)?p:a);try{reviewPeak(point.x,'Chart-picked');}catch(e){status(e.message);}};$('plot').replaceChildren(svg);
}
function search(){
 try{query=parseQuery($('query').value);const tolerance=Number($('tolerance').value);if(!$('tolerance').value)throw Error('Enter a tolerance.');const matches=matchBands(query,tolerance);
 $('result-title').textContent=`Matches ${query.min===query.max?'near':'within'} ${number(query.min)}${query.min===query.max?'':`–${number(query.max)}`} cm⁻¹`;
 $('result-count').textContent=`${matches.length} possible ${matches.length===1?'assignment':'assignments'}`;
 $('results').replaceChildren();
 for(const b of matches){const card=element('article',undefined,'result'),top=element('div',undefined,'result-top'),heading=element('h3',b.group);heading.append(element('span',b.bond,'bond'));top.append(heading,element('span',`${b.min}–${b.max} cm⁻¹`,'range'));card.append(top,element('p',`${b.distance===0?'Direct range overlap':`${number(b.distance)} cm⁻¹ from the reference range`} · Reference intensity: ${b.intensity}`));const details=element('details');details.append(element('summary','Inspect evidence & source'),element('p',`${b.evidence}. Reference guidance; no validation of your sample. Overlapping bands and measurement conditions may change the interpretation.`),element('p',`${b.source.author} · ${b.source.title} · ${b.source.year}. Reviewed ${b.source.reviewed}. ${b.source.license}.`));const link=element('a','Open source table');link.href=b.source.url;link.target='_blank';link.rel='noreferrer';details.append(link);card.append(details);$('results').append(card);}
 for(const [i,b] of matches.entries())if(b.note){const card=$('results').children[i];card.insertBefore(element('p',b.note),card.querySelector('details'));card.querySelector('p').textContent=b.evidence;card.querySelector('details p').textContent=b.evidence+'. No sample-specific validation; screening proximity is not confirmation.';card.querySelector('details a').textContent='Open reference source';card.querySelector('.range').textContent=`Near ${b.center} cm⁻¹`;card.querySelector('details').append(element('p',`${b.rangeKind}: ${b.min}–${b.max} cm⁻¹. Source position, not a measured band width.`));}
 if(!matches.length)$('results').append(element('p','No matching bands in this limited reference set. This does not establish that a functional group is absent.','muted'));
 $('peaks').replaceChildren();for(const p of peaks){const button=element('button',number(p.x)+' cm⁻¹');button.onclick=()=>{$('query').value=p.x.toFixed(2);search();};$('peaks').append(button);}plot(matches);renderReview();renderPatterns();return true;
 }catch(e){status(e.message);return false;}
}
function analyze(){
 if(!spectrum)return;comparison=null;referencePoints=null;
 detectionSettings={contrast:Number($('contrast').value),separation:Number($('separation').value),smooth:$('smooth').checked,method:'contour-prominence'};
 try{const threshold=Number($('contrast').value),separation=Number($('separation').value);if(!$('contrast').value||threshold<0.1||threshold>100||!$('separation').value||separation<1||separation>500)throw Error('Use prominence 0.1–100% and separation 1–500 cm⁻¹.');
 processed=preprocess(spectrum.points,$('type').value,{window:Number($('window').value),baseline:$('baseline').checked});detectionSettings={...detectionSettings,window:Number($('window').value),baseline:$('baseline').checked};peaks=detectPeaks(processed,$('type').value,threshold,separation,$('smooth').checked).map(p=>({...p,y:spectrum.points.find(q=>q.x===p.x).y}));status(`${peaks.length} candidate peaks. Raw trace: blue; processed trace: orange. ${spectrum.warnings.join(' ')} Review candidates before interpreting.`);search();
 }catch(e){peaks=[];$('peaks').replaceChildren();search();status(e.message);}
}
function load(data,name){zoom=null;spectrum=data;processed=null;comparison=null;referencePoints=null;peaks=[];detectionSettings=null;$('file-name').textContent=name;$('plot-title').textContent='Your spectrum';$('plot-badge').textContent='Raw measurements';$('plot-note').textContent=`${data.points.length.toLocaleString()} samples · ${number(data.points[0].x)}–${number(data.points.at(-1).x)} cm⁻¹. Select intensity type, then detect candidates. No baseline correction applied.`;$('analysis-controls').hidden=false;$('peaks').replaceChildren();status(`Loaded locally. ${data.warnings.join(' ')} Confirm the intensity type before detection.`);search();}
 $('search-form').onsubmit=e=>{e.preventDefault();status('');search();};
 document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{$('query').value=b.dataset.query;status('');search();});
 $('csv').onchange=async()=>{const file=$('csv').files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('File exceeds 5 MB.');const data=await readSpectrumFile(file);if(data)load(data,file.name);}catch(e){status(e.message);}finally{$('csv').value='';}};
 $('demo').onclick=()=>{const points=[];for(let x=400;x<=4000;x+=2){let y=96;for(const [center,width,height]of [[3420,90,23],[2920,24,12],[1715,18,62],[1120,22,32]])y-=height*Math.exp(-.5*((x-center)/width)**2);points.push({x,y});}$('type').value='transmittance';load({points,warnings:['Synthetic example, not an experimental or reference spectrum.']},'Synthetic demonstration');analyze();};
 const review=element('section',undefined,'panel');review.id='peak-review';$('results').closest('section').after(review);
 let detectionSettings=null;
 $('smooth').closest('label').hidden=true;const processingControls=element('div'),windowLabel=element('label','Smoothing window (samples)'),windowSelect=element('select');windowSelect.id='window';windowLabel.htmlFor='window';for(const n of [1,5,11,21]){const option=element('option',n===1?'None':`${n} samples`);option.value=n;windowSelect.append(option);}const baselineLabel=element('label',undefined,'check'),baseline=element('input');baseline.type='checkbox';baseline.id='baseline';baselineLabel.append(baseline,document.createTextNode('Endpoint baseline correction (absorbance only)'));processingControls.append(windowLabel,windowSelect,baselineLabel,element('p','Endpoint correction subtracts a straight line between the first and last raw samples. Broad bands and contaminated endpoints can bias it.','muted'));$('analyze').before(processingControls);
 const referenceLabel=element('label','Compare a reference (same intensity type)'),referenceInput=element('input');referenceInput.type='file';referenceInput.accept='.csv,.txt,.tsv,.xlsx';referenceInput.id='reference-csv';referenceLabel.htmlFor=referenceInput.id;$('analysis-controls').append(referenceLabel,referenceInput);referenceInput.onchange=async()=>{try{if(!spectrum)throw Error('Load your spectrum first.');const file=referenceInput.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('Reference exceeds 5 MB.');const imported=await readSpectrumFile(file);if(!imported)return;const ref=imported.points;referencePoints=preprocess(ref,$('type').value,{window:detectionSettings?.window??1,baseline:detectionSettings?.baseline??false});comparison={file:file.name,...compareSpectra(processed??spectrum.points,referencePoints)};status(`Shape correlation: ${comparison.correlation.toFixed(3)} over ${comparison.samples} samples. ${comparison.limitation}`);search();}catch(e){status(e.message);}finally{referenceInput.value='';}};
 const tools=element('div',undefined,'review-actions');for(const [label,action]of [['Export chart SVG',()=>{const svg=$('plot').querySelector('svg');saveBlob(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}),'ftir-chart.svg');}],['Save session',()=>{saveBlob(new Blob([JSON.stringify({version:1,spectrum,peaks,query:$('query').value,tolerance:$('tolerance').value,type:$('type').value,detectionSettings})],{type:'application/json'}),'ftir-session.json');}]]){const button=element('button',label);button.onclick=action;tools.append(button);}$('plot-note').after(tools);
 const sessionLabel=element('label','Restore local session'),sessionInput=element('input');sessionInput.type='file';sessionInput.accept='.json';sessionLabel.htmlFor='session-file';sessionInput.id='session-file';$('analysis-controls').after(sessionLabel,sessionInput);sessionInput.onchange=async()=>{try{const file=sessionInput.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('Session exceeds 10 MB.');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.peaks)||data.peaks.length>50000||data.peaks.some(p=>!Number.isFinite(p.x)||p.x<400||p.x>4000))throw Error('Invalid session peaks.');parseQuery(data.query);if(!['absorbance','transmittance'].includes(data.type))throw Error('Invalid intensity type.');matchBands({min:400,max:400},Number(data.tolerance));if(data.spectrum){const validated=parseCSV(data.spectrum.points.map(p=>`${p.x},${p.y}`).join('\n'));load(validated,'Restored session');}else{zoom=null;spectrum=null;processed=null;comparison=null;referencePoints=null;}peaks=data.peaks;$('query').value=data.query;$('tolerance').value=data.tolerance;$('type').value=data.type;detectionSettings=data.detectionSettings??null;search();status('Session restored locally. Re-run detection to reconstruct preprocessing.');}catch(e){status(`Unable to restore: ${e.message}`);}finally{sessionInput.value='';}};
 function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function renderPatterns(){const section=element('div');section.append(element('h3','Supporting-band checks'));for(const pattern of patterns){const found=pattern.ids.filter(id=>peaks.some(p=>matchBands({min:p.x,max:p.x},Number($('tolerance').value)).some(b=>b.id===id)));if(!found.length)continue;const row=element('p',`${pattern.name}: ${found.length}/${pattern.ids.length} reference regions represented. `,'muted'),link=element('a','Inspect source');link.href=pattern.source.url;link.target='_blank';link.rel='noreferrer';row.append(link);section.append(row);}section.append(element('p','Counts describe positional coverage, not confidence. One peak can overlap multiple reference entries; undetected bands are not proof of absence.','muted'));if(comparison)section.append(element('p',`Reference overlay: purple dashed, independently scaled. Reference: ${comparison.file} · shape correlation ${comparison.correlation.toFixed(3)}. ${comparison.limitation}`,'muted'));review.append(section);}
 $('analyze').onclick=analyze;
 const manual=element('form',undefined,'manual-form'),manualLabel=element('label','Add a reviewed peak (cm⁻¹)'),manualInput=element('input');manualInput.id='manual-peak';manualInput.placeholder='e.g. 874.6';manualLabel.htmlFor=manualInput.id;const add=element('button','Add peak','secondary');add.type='submit';manual.append(manualLabel,manualInput,add);$('analysis-controls').after(manual);
 function reviewPeak(position,origin,index=null){const q=parseQuery(String(position));if(q.min!==q.max)throw Error('Enter one peak position.');if(peaks.some((p,i)=>i!==index&&Math.abs(p.x-q.min)<.01))throw Error('That peak is already in the review.');const peak={x:q.min,origin},point=spectrum?.points.reduce((a,p)=>Math.abs(p.x-q.min)<Math.abs(a.x-q.min)?p:a);if(point&&q.min>=spectrum.points[0].x&&q.min<=spectrum.points.at(-1).x)peak.y=point.y;if(index===null)peaks.push(peak);else peaks[index]=peak;search();status('Reviewed peak saved. Assignments remain provisional.');}
 manual.onsubmit=e=>{e.preventDefault();try{reviewPeak(manualInput.value,'Manual');manualInput.value='';}catch(e){status(e.message);}};
 function editPeak(index){const dialog=element('dialog',undefined,'import-dialog'),form=element('form'),input=element('input'),label=element('label','Peak position (cm-1)'),error=element('p'),actions=element('div',undefined,'dialog-actions');input.id='edit-position';input.value=peaks[index].x;label.htmlFor=input.id;error.setAttribute('role','alert');for(const [text,icon]of [['Cancel','close-circle-linear'],['Save','check-circle-linear']]){const button=element('button'),img=element('img');img.src='assets/icons/'+icon+'.svg';img.alt='';img.width=18;img.height=18;button.append(img,document.createTextNode(text));button.type=text==='Save'?'submit':'button';if(text==='Cancel')button.onclick=()=>dialog.close();actions.append(button);}form.append(element('h2','Edit reviewed peak'),label,input,error,actions);dialog.append(form);document.body.append(dialog);form.onsubmit=e=>{e.preventDefault();try{reviewPeak(input.value,'Edited',index);dialog.close();}catch(e){error.textContent=e.message;}};dialog.onclose=()=>dialog.remove();dialog.showModal();input.focus();input.select();}
 const viewForm=element('form',undefined,'view-toolbar'),viewLabel=element('label','View range (cm-1)'),viewInput=element('input'),apply=element('button','Zoom'),reset=element('button','Reset view'),pickLabel=element('label',undefined,'check'),pick=element('input');viewInput.id='view-range';viewInput.placeholder='1000-1800';viewLabel.htmlFor=viewInput.id;apply.type='submit';reset.type='button';pick.type='checkbox';pick.id='chart-pick';pickLabel.append(pick,document.createTextNode('Click trace to add a peak'));viewForm.append(viewLabel,viewInput,apply,reset,pickLabel);$('plot').before(viewForm);viewForm.onsubmit=e=>{e.preventDefault();try{const q=parseQuery(viewInput.value);if(q.min===q.max)throw Error('Enter two different endpoints.');if(spectrum&&!spectrum.points.some(p=>p.x>=q.min&&p.x<=q.max))throw Error('No measured samples in this range.');zoom=q;search();status('View zoomed. Raw measurements are preserved.');}catch(e){status(e.message);}};reset.onclick=()=>{zoom=null;viewInput.value='';search();status('Full view restored.');};
 function currentReport(){return buildReport(peaks,Number($('tolerance').value),{file:$('file-name').textContent,intensityType:spectrum?$('type').value:null,detectionSettings,comparison,referenceVersion:'2026-10-09.3'});}
 function download(format){const report=currentReport();const blob=new Blob([format==='json'?JSON.stringify(report,null,2):format==='html'?reportHTML(report):reportCSV(report)],{type:format==='json'?'application/json':format==='html'?'text/html;charset=utf-8':'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=`ftir-analysis.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Analysis exported locally. Includes source links and uncertainty notes.');}
 function renderReview(){review.replaceChildren();review.append(element('p','SPECTRUM ANALYSIS','eyebrow'),element('h2','Review every candidate'),element('p',`${peaks.length} peaks · ${peaks.filter(p=>matchBands({min:p.x,max:p.x},Number($('tolerance').value)).length).length} with reference candidates. Overlapping assignments are retained.`,'muted'));if(!peaks.length){review.append(element('p','Detect peaks from a spectrum or add a position manually to build an analysis.','muted'));return;}const actions=element('div',undefined,'review-actions');for(const format of ['csv','json','html']){const button=element('button',`Export ${format.toUpperCase()}`);button.onclick=()=>download(format);actions.append(button);}review.append(actions);const wrapper=element('div',undefined,'table-scroll'),table=element('table'),head=element('thead'),tr=element('tr');for(const label of ['Peak (cm⁻¹)','Possible assignments','Review']){const th=element('th',label);th.scope='col';tr.append(th);}head.append(tr);table.append(head);const body=element('tbody');for(const [i,p]of peaks.entries()){const row=element('tr'),pos=element('td'),button=element('button',number(p.x));button.onclick=()=>{$('query').value=p.x.toFixed(2);search();};pos.append(button,element('p',p.origin??'Detected','muted'));const matches=matchBands({min:p.x,max:p.x},Number($('tolerance').value));const names=element('td',matches.length?[...new Set(matches.map(b=>b.group))].join(' · '):'Unmatched — limited coverage'),action=element('td'),remove=element('button','Remove');remove.setAttribute('aria-label',`Remove peak ${number(p.x)}`);remove.onclick=()=>{peaks.splice(i,1);search();};const edit=element('button','Edit');edit.setAttribute('aria-label','Edit peak '+number(p.x));edit.onclick=()=>editPeak(i);action.append(edit,remove);row.append(pos,names,action);body.append(row);}table.append(body);wrapper.append(table);review.append(wrapper,element('p','Select a position to inspect evidence. Removing a candidate changes the review and export, not the raw spectrum.','muted'));}
 styleFileInput($('csv'),'Choose spectrum');styleFileInput(referenceInput,'Choose reference');styleFileInput(sessionInput,'Restore session'); $('type').onchange=()=>{peaks=[];processed=null;comparison=null;referencePoints=null;detectionSettings=null;$('peaks').replaceChildren();search();status('Intensity type changed. Run detection again.');};search();
