import {matchBands} from './science.js?v=8';
import {patterns} from './references.js?v=8';
export function supportingChecks(peaks,tolerance){return patterns.map(pattern=>({...pattern,represented:pattern.ids.filter(id=>peaks.some(p=>matchBands({min:p.x,max:p.x},tolerance).some(b=>b.id===id)))})).filter(p=>p.represented.length);}
export function buildReport(peaks,tolerance,metadata){
 return {version:2,createdAt:new Date().toISOString(),metadata,tolerance,supportingChecks:supportingChecks(peaks,tolerance),limitation:'Candidate assignments only; not compound identification. Unmatched peaks indicate limited reference coverage. Supporting-band counts describe positional coverage, not confidence.',peaks:peaks.map(p=>({...p,assignments:matchBands({min:p.x,max:p.x},tolerance)}))};
}
export function reportHTML(report){const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return `<!doctype html><html lang="en"><meta charset="utf-8"><title>FT-IR analysis report</title><style>body{font:15px system-ui;max-width:1000px;margin:40px auto;padding:20px;color:#202125}h1{letter-spacing:-1px}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #ddd;padding:12px;text-align:left;vertical-align:top}small,p{line-height:1.7}a{color:#0066cc}@media print{body{margin:0}}</style><h1>FT-IR analysis report</h1><p>${esc(report.metadata.file)} · ${esc(report.createdAt)}<br>Intensity: ${esc(report.metadata.intensityType??'Not specified')} · Tolerance: ${esc(report.tolerance)} cm⁻¹</p><p>${esc(report.limitation)}</p><h2>Reviewed peaks</h2><table><thead><tr><th>cm⁻¹</th><th>Possible assignments and evidence</th></tr></thead><tbody>${report.peaks.map(p=>`<tr><td>${esc(p.x)}<br><small>${esc(p.origin??'Detected')}</small></td><td>${p.assignments.length?p.assignments.map(b=>`<p><strong>${esc(b.group)} · ${esc(b.bond)}</strong><br>${esc(b.rangeKind??'Reference range')}: ${esc(b.min)}–${esc(b.max)} cm⁻¹<br><small>${esc(b.note??b.evidence)}<br><a href="${esc(b.source.url)}">${esc(b.source.author)} · ${esc(b.source.title)}</a> · ${esc(b.source.license)}</small></p>`).join(''):'Unmatched in the limited reference set'}</td></tr>`).join('')}</tbody></table><h2>Supporting-band checks</h2>${report.supportingChecks.map(p=>`<p>${esc(p.name)}: ${p.represented.length}/${p.ids.length} regions represented. <a href="${esc(p.source.url)}">Source</a></p>`).join('')||'<p>No represented patterns.</p>'}<h2>Processing settings</h2><pre>${esc(JSON.stringify(report.metadata.detectionSettings,null,2))}</pre><p>Reference data adapted from OpenStax: CC BY-NC-SA 4.0. Access for free at <a href="https://openstax.org/books/organic-chemistry/pages/1-why-this-chapter">OpenStax</a>.</p></html>`;}
export function reportCSV(report){
 const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';
 const rows=[['Wavenumber (cm-1)','Origin','Group','Bond','Reference min','Reference max','Reference type','Distance (cm-1)','Evidence','Source','URL','Limitations']];
 for(const p of report.peaks){const matches=p.assignments.length?p.assignments:[null];for(const b of matches)rows.push([p.x,p.origin??'Detected',b?.group??'Unmatched',b?.bond,b?.min,b?.max,b?.rangeKind??'Reference range',b?.distance,b?.evidence,b?`${b.source.author}; ${b.source.publisher}; ${b.source.title}; ${b.source.license}`:'',b?.source.url,b?.note??report.limitation]);}
 return rows.map(row=>row.map(quote).join(',')).join('\r\n');
}
